### ISSUE TITLE
[BUG] wp.constant(wp.int32(IntEnum_value)) fails to compile on Warp 1.12.1 — CUDA sees ParticleFlags.ACTIVE instead of 1

### ISSUE THREAD

**Issue by antopio26** [newton-physics/newton#2363]
### Description
The file `newton/_src/viewer/kernels.py` defines a constant using a Python `IntEnum`:

```python
PARTICLE_ACTIVE = wp.constant(wp.int32(newton.ParticleFlags.ACTIVE))
```

In **Warp 1.12.1**, passing an `IntEnum` value through `wp.int32()` into `wp.constant()` causes the codegen to emit the symbolic name verbatim into the CUDA source rather than resolving it to its underlying integer value. This results in the following compilation error:

> **Error:** `wp_newton._src.viewer.kernels_e303421.cu(8360): error: identifier "ParticleFlags" is undefined`
> `const wp::int32 var_2 = ParticleFlags.ACTIVE;`

This raises `NVRTC_ERROR_COMPILATION` (error code 6) and crashes any code path triggering the compilation of the viewer kernels module, such as `ViewerGL.set_model()`.

---

### Minimal Reproducer
The following snippet demonstrates the failure on Warp 1.12.1:

```python
import warp as wp
from enum import IntEnum

class MyFlags(IntEnum):
    ACTIVE = 1

# Fails — emits "MyFlags.ACTIVE" directly into CUDA source
MY_CONST = wp.constant(wp.int32(MyFlags.ACTIVE))

@wp.kernel
def test_kernel():
    x = MY_CONST  # Triggers compilation failure

wp.launch(test_kernel, dim=1, inputs=[])
```

---

### Workaround
Explicitly coerce the enum member to a plain Python `int` before passing it to `wp.constant`:

```python
# Fixed definition
PARTICLE_ACTIVE = wp.constant(wp.int32(int(newton.ParticleFlags.ACTIVE)))
```

---

### Expected Behavior
`wp.int32(some_int_enum_value)` should produce the same CUDA constant as `wp.int32(1)`, as `IntEnum` is a subclass of `int`. 

1.  **Warp** should handle `IntEnum` transparently during codegen.
2.  **Newton** should defensively cast with `int()` at the definition site to ensure compatibility across Warp versions.

> [!NOTE]
> This appears to be a regression in **Warp 1.12.x**. Older versions likely handled `IntEnum` correctly via a different codegen path.

### Reproduction Script

```python
import warp as wp
from enum import IntEnum

class MyFlags(IntEnum):
    ACTIVE = 1

# Fails — emits "MyFlags.ACTIVE" directly into CUDA source
MY_CONST = wp.constant(wp.int32(MyFlags.ACTIVE))

@wp.kernel
def test_kernel():
    x = MY_CONST  # Triggers compilation failure

wp.launch(test_kernel, dim=1, inputs=[])
```

### System Information

- **Newton:** `release-1.1` (installed from source)
- **Warp:** `1.12.1`
- **CUDA Toolkit:** `12.9` / **Driver:** `13.0`

**Comment by Kenny-Vilella** [comment]
Are you using python 3.10?
I saw something similar with python 3.10, but it seems to work with python 3.11+.

**Comment by antopio26** [comment]
I am going to test this and tell you if it solves the problem. Thanks for the fast answer!

**Comment by antopio26** [comment]
@Kenny-Vilella I can confirm this is working with python 3.12.3

**Comment by shi-eric** [comment]
Hi, can you please file this issue in https://github.com/NVIDIA/warp/issues ?

**Comment by antopio26** [comment]
Will do as soon as possible

**Comment by c0d1f1ed** [comment]
Fixed in https://github.com/NVIDIA/warp/commit/eb627ef8303f86ee94ba30b2601f2071d24c8e4e
