### ISSUE TITLE
Newton backend: `Articulation.set_joint_position_targets()` triggers Warp CUDA error 710 (device-side assert) and kills the entire CUDA context — physics, RTX rendering and WebRTC — Isaac Sim 6.1.0

### ISSUE THREAD

**Issue by ShrE333** [newton-physics/newton#4219]
**Post title:** Newton backend: `Articulation.set_joint_position_targets()` triggers Warp CUDA error 710 (device-side assert) and kills the entire CUDA context — physics, RTX rendering and WebRTC — Isaac Sim 6.1.0

## Summary

On Isaac Sim 6.1.0 with the Newton physics backend, writing articulation joint
position targets via the `isaacsim.core.prims.Articulation` API immediately
triggers a device-side assert in Warp (`CUDA error 710`). After that, **every
CUDA operation in the process fails** — Newton simulation steps, RTX texture
allocation, rendering, and the WebRTC livestream. The app must be restarted;
there is no in-process recovery.

Read-side calls on the same Articulation handle (`dof_names`,
`get_joint_positions()`) work fine, so the articulation is alive and correctly
constructed inside Newton. Only the target-write path kills the context.

## Environment

- Isaac Sim **6.1.0** (installed at `/home/coho/IsaacSim-6.1.0`), Linux x86_64, Ubuntu 24.04.3 LTS
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 595.84                 Driver Version: 595.84         CUDA Version: 13.2     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 5090        Off |   00000000:01:00.0  On |                  N/A |
| 33%   58C    P1            151W /  575W |    4703MiB /  32607MiB |     57%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
- GPU: RTX 5090 , driver 595.84, CUDA 13.2
- Physics backend: **Newton** (MuJoCo Warp / MJWarp — `mujoco.warp_src.*` modules load at startup)
- Running via **WebRTC livestream** (GLFW windowing unavailable in this environment)
- Core API backend: **torch** (per `isaacsim.core.utils.torch.tensor.move_data` in the traceback)
- `nconmax` raised to 1000 per the Newton documentation [1] to clear
  "Number of Newton contacts exceeded MJWarp limit (200)" warnings [2]

## Scene

Custom procedurally-generated USD stage (upAxis Z, metersPerUnit 1,
timeCodesPerSecond 240). Static kitchen geometry (all colliders are boxes, no
colliding triangle meshes) plus one USD Physics articulation,
`/World/DishwasherArticulation`:

- `ArticulationRootAPI` on the articulation Xform
- 4 rigid bodies: Anchor (40 kg, fixed to world via FixedJoint), Door (8 kg,
  RevoluteJoint `DoorHinge`, axis X, limits 0–95 deg, angular force drive
  k=600 d=60 maxForce=600), UpperTray + LowerTray (4 kg each, PrismaticJoint
  Y-axis slides, linear force drives k=500 d=60)
- 3 DOFs total; `dof_names` as reported by the API:
  `['DoorHinge', 'LowerTraySlide', 'UpperTraySlide']`
- 32 colliders, zero penetrating pairs (verified with an AABB pair audit)

## Reproduction

**Part 1 — run in the Script Editor while STOPPED** (creates a minimal
driven articulation mirroring the structure above):

```python
import omni.usd
from pxr import UsdGeom, UsdPhysics, Gf, Sdf

stage = omni.usd.get_context().get_stage()
root = UsdGeom.Xform.Define(stage, "/World/MiniArt")
UsdPhysics.ArticulationRootAPI.Apply(root.GetPrim())

anchor = UsdGeom.Xform.Define(stage, "/World/MiniArt/Anchor")
anchor.AddTranslateOp().Set(Gf.Vec3d(0.0, 0.0, 1.0))
rb = UsdPhysics.RigidBodyAPI.Apply(anchor.GetPrim())
rb.CreateRigidBodyEnabledAttr(True)
UsdPhysics.MassAPI.Apply(anchor.GetPrim()).CreateMassAttr(10.0)

fj = UsdPhysics.FixedJoint.Define(stage, "/World/MiniArt/RootFixed")
fj.CreateBody0Rel().SetTargets([Sdf.Path("/World/MiniArt/Anchor")])
fj.CreateLocalPos0Attr().Set(Gf.Vec3f(0, 0, 0))
fj.CreateLocalPos1Attr().Set(Gf.Vec3f(0, 0, 1))
fj.CreateCollisionEnabledAttr(False)

door = UsdGeom.Xform.Define(stage, "/World/MiniArt/Door")
door.AddTranslateOp().Set(Gf.Vec3d(0.0, -0.105, 1.45))
rb = UsdPhysics.RigidBodyAPI.Apply(door.GetPrim())
rb.CreateRigidBodyEnabledAttr(True)
UsdPhysics.MassAPI.Apply(door.GetPrim()).CreateMassAttr(2.0)

col = UsdGeom.Cube.Define(stage, "/World/MiniArt/Door/Col")
col.CreateSizeAttr(0.2)
UsdGeom.Xformable(col).AddScaleOp().Set(Gf.Vec3f(0.3, 0.03, 0.7))
UsdPhysics.CollisionAPI.Apply(col.GetPrim())

hj = UsdPhysics.RevoluteJoint.Define(stage, "/World/MiniArt/DoorHinge")
hj.CreateBody0Rel().SetTargets([Sdf.Path("/World/MiniArt/Anchor")])
hj.CreateBody1Rel().SetTargets([Sdf.Path("/World/MiniArt/Door")])
hj.CreateLocalPos0Attr().Set(Gf.Vec3f(0.0, -0.105, 0.1))
hj.CreateLocalPos1Attr().Set(Gf.Vec3f(0.0, 0.0, -0.35))
hj.CreateAxisAttr().Set(UsdPhysics.Tokens.x)
hj.CreateLowerLimitAttr().Set(0.0)
hj.CreateUpperLimitAttr().Set(95.0)
hj.CreateCollisionEnabledAttr(False)
drv = UsdPhysics.DriveAPI.Apply(hj.GetPrim(), "angular")
drv.CreateTypeAttr().Set("force")
drv.CreateTargetPositionAttr().Set(0.0)
drv.CreateStiffnessAttr().Set(600.0)
drv.CreateDampingAttr().Set(60.0)
drv.CreateMaxForceAttr().Set(600.0)
print("Part 1 done -- press Play, then run Part 2.")
```

**Press Play**, then **Part 2 — run while PLAYING**:

```python
import torch
from isaacsim.core.prims import Articulation

art = Articulation("/World/MiniArt")
try:
    art.initialize()
except Exception:
    pass
print("dof_names:", art.dof_names)              # works
print("positions:", art.get_joint_positions())  # works

# THIS call kills the CUDA context on Newton in 6.1.0:
art.set_joint_position_targets(
    torch.tensor([0.7854], dtype=torch.float32),  # 45 deg in radians
    torch.tensor([0], dtype=torch.long),
)
print("If you can read this, it did not crash for you.")
```

The original crash was on the full scene with 3 DOFs:
`set_joint_position_targets(torch.tensor([radians(45), -0.18, -0.18]), torch.tensor([0, 2, 1]))`.
If the minimal scene above does not reproduce it, the delta is scale (4 bodies
/ 4 joints / 32 colliders vs. 2 bodies) — I can provide the full USDA.

## Expected / Actual

- **Expected:** hinge commanded toward the target; door swings.
- **Actual:** immediate CUDA 710 cascade; all subsequent CUDA calls fail;
  rendering and WebRTC die; app must be restarted.

## Log excerpt (first occurrence of each distinct error)

```
Warp CUDA error 710: device-side assert triggered (in function wp_alloc_device_async,
  .../omni.warp.core/warp/warp/native/warp.cu:817)
[Error] [isaacsim.physics.newton.impl.fabric] [isaacsim.physics.newton] Failed to build fabric
  arrays: Failed to allocate 32 bytes on device 'cuda:0'. count=4, device=cuda:0
[Error] [omni.rtx] CUDA error in memcpy: device-side assert triggered:
  .../GpuCompute-Cuda.cpp:436 (device 0)
[Error] [carb.cudainterop.plugin] CUDA error 710: cudaErrorAssert - device-side assert triggered)
[Error] [carb.cudainterop.plugin] Failed to import external memory in CUDA
[Error] [omni.rtx] Cannot create cuda external memory for resource!
[Error] [omni.rtx] Texture creation failed for the device: 0.
[Error] [carb.scenerenderer-rtx.plugin] Failed to allocate 1280x720 LdrColor resource for device mask 0x1
[Warning] [rtx.hydra] Rendering failed.
[Error] [omni.usd.multitick.render] multiTickRateRender() returned null (partition 1/1)
Warp CUDA error 710: device-side assert triggered (in function wp_cuda_graph_launch,
  .../omni.warp.core/warp/warp/native/warp.cu:4543)
[Error] [isaacsim.physics.newton.impl.simulation_functions] [Newton] Simulation step error:
  Graph launch error: Warp CUDA error 710: ...
```
(Then repeats every frame; the WebRTC stream dies with the render pipeline.
Full log attached.)

## Isolation summary

| Operation (Newton, 6.1.0, while playing) | Result |
|---|---|
| `Articulation(path)` + `initialize()` | OK |
| `dof_names` | OK — `['DoorHinge', 'LowerTraySlide', 'UpperTraySlide']` |
| `get_joint_positions()` | OK |
| `set_joint_position_targets(torch tensors)` | **CUDA 710 → whole-context death** |
| `set_joint_position_targets(python list)` | `AttributeError: 'list' object has no attribute 'to'` in `move_data()` — separate minor issue: no list branch in the torch backend (no crash) |
| Live USD `DriveAPI` target writes while playing | No crash, but no actuation observed |
| Same stage, no core-API calls | Runs and steps fine for extended sessions |

## Possibly related observations

- The fabric failure reports `count=4` for a 32-byte allocation — matching the
  articulation's 4 rigid bodies / 4 joints; the fault may be in the write path
  building fabric arrays for the articulation.
- Device-side asserts are asynchronous, so the surfacing location (allocation)
  may not be the faulting kernel.
- An earlier session also logged `mujoco.warp_src.sensor` loading with an
  `(error)` status; unknown whether related.

## Questions

1. Is `set_joint_position_targets` (via the deprecated `isaacsim.core.prims`
   wrapper) expected to work on the Newton backend in 6.1.0?
2. If not, what is the currently supported way to command articulation joint
   targets live on Newton?
3. Is whole-context death (taking rendering and WebRTC down) expected behavior
   for a failed articulation write, or should this be contained/recoverable?

## References

[1] Newton physics docs (6.0.1): https://docs.isaacsim.omniverse.nvidia.com/6.0.1/physics/newton_physics.html
[2] Forum thread where nconmax=1000 was recommended: https://docs.isaacsim.omniverse.nvidia.com/6.0.1/physics/newton_physics.html
[3] Traceback frames: `isaacsim.core.prims/.../impl/articulation.py:861`
    (`set_joint_position_targets`), `isaacsim.core.utils/.../torch/tensor.py:142`
    (`move_data`), `omni.warp.core/warp/native/warp.cu:817` (`wp_alloc_device_async`),
    `warp.cu:4543` (`wp_cuda_graph_launch`)

**Attachments:** full session log; scene USDA available on request.
